language: node_js
node_js:
- 12
- 10

os: linux

addons:
  apt:
    # https://docs.cypress.io/guides/guides/continuous-integration.html#Example-travis-yml-config-file
    packages:
    - libgconf-2-4
  chrome: stable

# https://docs.cypress.io/guides/guides/continuous-integration.html#Example-travis-yml-config-file
cache:
  npm: true
  directories:
  - ~/.cache

install:
- npm ci

script:
- npm run test
- npm run dev &
# suppresses Percy snapshots uploading unless Node.js is 12.x
- if [[ $TRAVIS_NODE_VERSION != 12* ]]; then export PERCY_TOKEN=; fi
- npx wait-on http-get://localhost:8080 && npm run cypress:run
