version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Package installation
          command: npm install
      - run:
          name: Running unit tests
          command: npm test
