name: Continuous Integration on Push
on: push

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    # runs E2E test with Cypress
    # it also resolves dependencies
    - name: Run Cypress
      uses: cypress-io/github-action@v1
      with:
        build: npm run build
        start: npm run dev
        # this action uses `got` module instead of `wait-on`.
        # as `got` uses `GET` by default, the normal URL should work.
        wait-on: 'http://localhost:8080'
        # this action bypasses cypress:run command in package.json
        command-prefix: 'percy exec -- npx'
        cache-key: node-v${{ matrix.node-version }}-on-${{ runner.os }}-hash-${{ hashFiles('package-lock.json') }}
      env:
        PERCY_TOKEN: |
          ${{ ((endsWith(github.ref, '/actions') || endsWith(github.base_ref, '/master')) && secrets.NOT_ACTUALLY_A_SECRET) || '' }}
